ignore:
  - "cogment/api/"
  - "?eggs"
  - "**/__pycache__"
  - "**/cogment_*.yaml"
  - "**/*_pb2*.py"
  - "**/cog_settings.py"
license:
  CopyrightYear: 2021
  Author: "Artificial Intelligence Redefined <dev+cogment@ai-r.com>"
