stages:
    - lint
    - test
    - build
    - publish

.base:
    image: python:3.7
    variables:
        PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    before_script:
        - mkdir -p ${PIP_CACHE_DIR}
        - python -m venv .venv
        - source .venv/bin/activate
        - pip install -r requirements.txt
        - python -m setup develop
    cache: &default_cache
        - paths:
              - .cache/pip
        - key:
              files:
                  - requirements.txt
                  - setup.cfg
          paths:
              - ".venv"

.base_gh_ssh_agent:
    before_script:
        ## _Inspired by https://docs.gitlab.com/ee/ci/ssh_keys/_
        ##
        ## Install ssh-agent if not already installed.
        - "command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )"
        ## Run ssh-agent
        - eval $(ssh-agent -s)
        ## Add the private key file to ssh-agent
        - echo "$GH_REPO_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
        ## Create the SSH directory and give it the right permissions
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        ## Using the set $SSH_KNOWN_HOSTS to be able to verify remote servers public keys
        - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
        - chmod 644 ~/.ssh/known_hosts

pycodestyle:
    extends: .base
    stage: lint
    script:
        - pycodestyle

mypy:
    extends: .base
    stage: lint
    script:
        - mypy cogment/

apache_licenses_check:
    stage: lint
    image: registry.gitlab.com/ai-r/apache-license-checker:latest
    script:
        - apache-license-checker

shellcheck:
    image: koalaman/shellcheck-alpine:stable
    stage: lint
    before_script:
        - shellcheck --version
    script:
        - shellcheck $(find . -name '*.sh' | xargs)

shfmt:
    image: mvdan/shfmt:v3.1.0-alpine
    stage: lint
    before_script:
        - shfmt -version
    script:
        - shfmt -i 2 -ci -d .

check_dependencies_conflicts:
    image: python:3.7
    stage: test
    script:
        - ./scripts/check_dependencies_conflicts.sh

integration_test:
    extends: .base
    stage: test
    script:
        - pytest --launch-orchestrator
    artifacts:
        when: always
        reports:
            junit: integration_test_report.xml

build_sdist:
    extends: .base
    stage: build
    script:
        - python -m build
        - twine check dist/*
    artifacts:
        expire_in: 1 week
        paths:
            - dist/*.tar.gz
            - dist/*.whl

publish_to_pypi:
    extends: .base
    stage: publish
    script:
        - python -m build
        - python -m twine upload dist/* --non-interactive -u $PYPI_USERNAME -p $PYPI_PASSWORD
    only:
        - /^v[0-9]+\.[0-9]+\.[0-9]+(?:-[a-zA-Z0-9]+)?$/

publish_branch_to_github:
    extends: .base_gh_ssh_agent
    stage: publish
    script:
        - git checkout ${CI_COMMIT_BRANCH} # Checkout the branch not the sha1
        - git remote add downstream git@github.com:cogment/cogment-py-sdk.git
        - git fetch downstream ${CI_COMMIT_BRANCH}
        - git push --tags downstream ${CI_COMMIT_BRANCH}:${CI_COMMIT_BRANCH}
    only:
        - main
