stages:
  - lint
  - test
  - build

default:
  image: python:3.8
  before_script:
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
    - source $HOME/.poetry/env
    - poetry install

lint:
  stage: lint
  script:
    - poetry run task lint

test:
  stage: test
  script:
    - poetry run task test

test_build:
  stage: build
  script:
    - poetry build -f sdist
