stages:
  - lint
  - test
  - build
  - publish

.base_poetry:
  image: python:3.7
  before_script:
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
    - source $HOME/.poetry/env
    - poetry install

.base_docker:
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  variables:
      # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
      DOCKER_HOST: tcp://docker:2376
      DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

lint:
  extends: .base_poetry
  stage: lint
  script:
    - poetry run task lint

apache_licenses_check:
  stage: lint
  image: registry.gitlab.com/ai-r/apache-license-checker:latest
  script:
    - apache-license-checker

integration_test:
  extends: .base_docker
  stage: test
  variables:
    COGMENT_ORCHESTRATOR_IMAGE: "cogment/orchestrator:v1.0.0-alpha9"
    COGMENT_IMAGE: "cogment/cli:v1.0.0-alpha10"
    # COGMENT_ORCHESTRATOR_IMAGE: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/cogment-orchestrator:latest
    # COGMENT_IMAGE: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/cogment-cli:latest
  script:
    - docker build -t cogment/cogment-py-sdk-integration-test:$CI_JOB_ID --build-arg COGMENT_ORCHESTRATOR_IMAGE="$COGMENT_ORCHESTRATOR_IMAGE" --build-arg COGMENT_IMAGE="$COGMENT_IMAGE" -f integration_test.dockerfile .
    - docker run --rm  --volume $(pwd):/output  cogment/cogment-py-sdk-integration-test:$CI_JOB_ID
  artifacts:
    when: always
    reports:
      junit: integration_test_report.xml

build_sdist:
  extends: .base_poetry
  stage: build
  script:
    - poetry build -f sdist
  artifacts:
    expire_in: 1 week
    paths:
      - dist/*.tar.gz

publish_to_pypi:
  extends: .base_poetry
  stage: publish
  script:
    - poetry build -f sdist
    - poetry publish -u $PYPI_USERNAME -p $PYPI_PASSWORD
  only:
    - /^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+(?:-[[:alnum:]]+)?$/

publish_to_gitlab:
  extends: .base_poetry
  stage: publish
  script:
    - poetry config repositories.private https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/packages/pypi 
    - poetry version $(poetry version --short)+${CI_COMMIT_BRANCH}_${CI_COMMIT_SHORT_SHA}
    - poetry build -f sdist
    - poetry publish --repository private -u gitlab-ci-token -p $CI_JOB_TOKEN
  only:
    - develop

