# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='test_cogment_app',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\ndata.proto\x12\x10test_cogment_app\"\x0b\n\tEnvConfig\">\n\x0bTrialConfig\x12/\n\nenv_config\x18\x01 \x01(\x0b\x32\x1b.test_cogment_app.EnvConfig\"\r\n\x0bObservation\"\x16\n\x14My_actor_classAction\"\x18\n\x16My_agent_class_1Action\"\x18\n\x16My_agent_class_2Actionb\x06proto3'
)




_ENVCONFIG = _descriptor.Descriptor(
  name='EnvConfig',
  full_name='test_cogment_app.EnvConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=43,
)


_TRIALCONFIG = _descriptor.Descriptor(
  name='TrialConfig',
  full_name='test_cogment_app.TrialConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='env_config', full_name='test_cogment_app.TrialConfig.env_config', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=107,
)


_OBSERVATION = _descriptor.Descriptor(
  name='Observation',
  full_name='test_cogment_app.Observation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=122,
)


_MY_ACTOR_CLASSACTION = _descriptor.Descriptor(
  name='My_actor_classAction',
  full_name='test_cogment_app.My_actor_classAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=146,
)


_MY_AGENT_CLASS_1ACTION = _descriptor.Descriptor(
  name='My_agent_class_1Action',
  full_name='test_cogment_app.My_agent_class_1Action',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=172,
)


_MY_AGENT_CLASS_2ACTION = _descriptor.Descriptor(
  name='My_agent_class_2Action',
  full_name='test_cogment_app.My_agent_class_2Action',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=198,
)

_TRIALCONFIG.fields_by_name['env_config'].message_type = _ENVCONFIG
DESCRIPTOR.message_types_by_name['EnvConfig'] = _ENVCONFIG
DESCRIPTOR.message_types_by_name['TrialConfig'] = _TRIALCONFIG
DESCRIPTOR.message_types_by_name['Observation'] = _OBSERVATION
DESCRIPTOR.message_types_by_name['My_actor_classAction'] = _MY_ACTOR_CLASSACTION
DESCRIPTOR.message_types_by_name['My_agent_class_1Action'] = _MY_AGENT_CLASS_1ACTION
DESCRIPTOR.message_types_by_name['My_agent_class_2Action'] = _MY_AGENT_CLASS_2ACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EnvConfig = _reflection.GeneratedProtocolMessageType('EnvConfig', (_message.Message,), {
  'DESCRIPTOR' : _ENVCONFIG,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:test_cogment_app.EnvConfig)
  })
_sym_db.RegisterMessage(EnvConfig)

TrialConfig = _reflection.GeneratedProtocolMessageType('TrialConfig', (_message.Message,), {
  'DESCRIPTOR' : _TRIALCONFIG,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:test_cogment_app.TrialConfig)
  })
_sym_db.RegisterMessage(TrialConfig)

Observation = _reflection.GeneratedProtocolMessageType('Observation', (_message.Message,), {
  'DESCRIPTOR' : _OBSERVATION,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:test_cogment_app.Observation)
  })
_sym_db.RegisterMessage(Observation)

My_actor_classAction = _reflection.GeneratedProtocolMessageType('My_actor_classAction', (_message.Message,), {
  'DESCRIPTOR' : _MY_ACTOR_CLASSACTION,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:test_cogment_app.My_actor_classAction)
  })
_sym_db.RegisterMessage(My_actor_classAction)

My_agent_class_1Action = _reflection.GeneratedProtocolMessageType('My_agent_class_1Action', (_message.Message,), {
  'DESCRIPTOR' : _MY_AGENT_CLASS_1ACTION,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:test_cogment_app.My_agent_class_1Action)
  })
_sym_db.RegisterMessage(My_agent_class_1Action)

My_agent_class_2Action = _reflection.GeneratedProtocolMessageType('My_agent_class_2Action', (_message.Message,), {
  'DESCRIPTOR' : _MY_AGENT_CLASS_2ACTION,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:test_cogment_app.My_agent_class_2Action)
  })
_sym_db.RegisterMessage(My_agent_class_2Action)


# @@protoc_insertion_point(module_scope)
