# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rps.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rps.proto',
  package='rps',
  syntax='proto3',
  serialized_pb=_b('\n\trps.proto\x12\x03rps\"\x0b\n\tEnvConfig\"/\n\tGameState\x12\x10\n\x08p1_score\x18\x01 \x01(\x05\x12\x10\n\x08p2_score\x18\x02 \x01(\x05\"y\n\x0eGameStateDelta\x12\x1f\n\x06result\x18\x01 \x01(\x0e\x32\x0f.rps.HandResult\x12\"\n\x0bp1_decision\x18\x02 \x01(\x0e\x32\r.rps.Decision\x12\"\n\x0bp2_decision\x18\x03 \x01(\x0e\x32\r.rps.Decision\".\n\x0b\x41\x63torAction\x12\x1f\n\x08\x64\x65\x63ision\x18\x01 \x01(\x0e\x32\r.rps.Decision\"\x0b\n\tJudgeView\"0\n\x0bJudgeAction\x12!\n\x08\x64\x65\x63ision\x18\x01 \x01(\x0e\x32\x0f.rps.HandResult*.\n\nHandResult\x12\n\n\x06P1_WON\x10\x00\x12\n\n\x06P2_WON\x10\x01\x12\x08\n\x04\x44RAW\x10\x02*6\n\x08\x44\x65\x63ision\x12\x08\n\x04NONE\x10\x00\x12\x08\n\x04ROCK\x10\x01\x12\t\n\x05PAPER\x10\x02\x12\x0b\n\x07SCISSOR\x10\x03\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_HANDRESULT = _descriptor.EnumDescriptor(
  name='HandResult',
  full_name='rps.HandResult',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='P1_WON', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='P2_WON', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DRAW', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=314,
  serialized_end=360,
)
_sym_db.RegisterEnumDescriptor(_HANDRESULT)

HandResult = enum_type_wrapper.EnumTypeWrapper(_HANDRESULT)
_DECISION = _descriptor.EnumDescriptor(
  name='Decision',
  full_name='rps.Decision',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ROCK', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PAPER', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SCISSOR', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=362,
  serialized_end=416,
)
_sym_db.RegisterEnumDescriptor(_DECISION)

Decision = enum_type_wrapper.EnumTypeWrapper(_DECISION)
P1_WON = 0
P2_WON = 1
DRAW = 2
NONE = 0
ROCK = 1
PAPER = 2
SCISSOR = 3



_ENVCONFIG = _descriptor.Descriptor(
  name='EnvConfig',
  full_name='rps.EnvConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=29,
)


_GAMESTATE = _descriptor.Descriptor(
  name='GameState',
  full_name='rps.GameState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='p1_score', full_name='rps.GameState.p1_score', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='p2_score', full_name='rps.GameState.p2_score', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=78,
)


_GAMESTATEDELTA = _descriptor.Descriptor(
  name='GameStateDelta',
  full_name='rps.GameStateDelta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='rps.GameStateDelta.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='p1_decision', full_name='rps.GameStateDelta.p1_decision', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='p2_decision', full_name='rps.GameStateDelta.p2_decision', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=201,
)


_ACTORACTION = _descriptor.Descriptor(
  name='ActorAction',
  full_name='rps.ActorAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='decision', full_name='rps.ActorAction.decision', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=249,
)


_JUDGEVIEW = _descriptor.Descriptor(
  name='JudgeView',
  full_name='rps.JudgeView',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=262,
)


_JUDGEACTION = _descriptor.Descriptor(
  name='JudgeAction',
  full_name='rps.JudgeAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='decision', full_name='rps.JudgeAction.decision', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=264,
  serialized_end=312,
)

_GAMESTATEDELTA.fields_by_name['result'].enum_type = _HANDRESULT
_GAMESTATEDELTA.fields_by_name['p1_decision'].enum_type = _DECISION
_GAMESTATEDELTA.fields_by_name['p2_decision'].enum_type = _DECISION
_ACTORACTION.fields_by_name['decision'].enum_type = _DECISION
_JUDGEACTION.fields_by_name['decision'].enum_type = _HANDRESULT
DESCRIPTOR.message_types_by_name['EnvConfig'] = _ENVCONFIG
DESCRIPTOR.message_types_by_name['GameState'] = _GAMESTATE
DESCRIPTOR.message_types_by_name['GameStateDelta'] = _GAMESTATEDELTA
DESCRIPTOR.message_types_by_name['ActorAction'] = _ACTORACTION
DESCRIPTOR.message_types_by_name['JudgeView'] = _JUDGEVIEW
DESCRIPTOR.message_types_by_name['JudgeAction'] = _JUDGEACTION
DESCRIPTOR.enum_types_by_name['HandResult'] = _HANDRESULT
DESCRIPTOR.enum_types_by_name['Decision'] = _DECISION

EnvConfig = _reflection.GeneratedProtocolMessageType('EnvConfig', (_message.Message,), dict(
  DESCRIPTOR = _ENVCONFIG,
  __module__ = 'rps_pb2'
  # @@protoc_insertion_point(class_scope:rps.EnvConfig)
  ))
_sym_db.RegisterMessage(EnvConfig)

GameState = _reflection.GeneratedProtocolMessageType('GameState', (_message.Message,), dict(
  DESCRIPTOR = _GAMESTATE,
  __module__ = 'rps_pb2'
  # @@protoc_insertion_point(class_scope:rps.GameState)
  ))
_sym_db.RegisterMessage(GameState)

GameStateDelta = _reflection.GeneratedProtocolMessageType('GameStateDelta', (_message.Message,), dict(
  DESCRIPTOR = _GAMESTATEDELTA,
  __module__ = 'rps_pb2'
  # @@protoc_insertion_point(class_scope:rps.GameStateDelta)
  ))
_sym_db.RegisterMessage(GameStateDelta)

ActorAction = _reflection.GeneratedProtocolMessageType('ActorAction', (_message.Message,), dict(
  DESCRIPTOR = _ACTORACTION,
  __module__ = 'rps_pb2'
  # @@protoc_insertion_point(class_scope:rps.ActorAction)
  ))
_sym_db.RegisterMessage(ActorAction)

JudgeView = _reflection.GeneratedProtocolMessageType('JudgeView', (_message.Message,), dict(
  DESCRIPTOR = _JUDGEVIEW,
  __module__ = 'rps_pb2'
  # @@protoc_insertion_point(class_scope:rps.JudgeView)
  ))
_sym_db.RegisterMessage(JudgeView)

JudgeAction = _reflection.GeneratedProtocolMessageType('JudgeAction', (_message.Message,), dict(
  DESCRIPTOR = _JUDGEACTION,
  __module__ = 'rps_pb2'
  # @@protoc_insertion_point(class_scope:rps.JudgeAction)
  ))
_sym_db.RegisterMessage(JudgeAction)


# @@protoc_insertion_point(module_scope)
